### ISSUE TITLE
Pressing command (Mac) closes sidebar navigation menu category

### ISSUE THREAD

**Issue by andyfleming** [laravel/docs#3284] opened 2017-04-24 04:09 UTC
After clicking on a navigation menu, I went to command-click a link to open it in a new tab and the sub-menu closed.

This consistently happens for me in `Google Chrome Version 58.0.3029.81 (64-bit)`

## Steps to reproduce

1. Open a docs page (like https://laravel.com/docs/5.4/configuration)
2. Click on a different navigation category on the left.
3. Press/hold command key.
4. Menu closes (so there is no way to command-click a link).

-----

**Video Attached:** [laravel_docs_command_click.mov.zip](https://github.com/laravel/docs/files/950404/laravel_docs_command_click.mov.zip)

**Comment by RamonSmit** [comment] 2017-04-24 13:13
Reproduced in here
`MacOS 10.12.4 Sierra with Google Chrome Version 57.0.2987.133 (64-bit)`

**Comment by Kyslik** [comment] 2017-04-24 15:49
Duplicate of https://github.com/laravel/docs/issues/3277

**Comment by cjcodes** [comment] 2017-05-26 20:04
Happens with _all_ keyboard input on Chrome in Linux. The JS event bind seems to go away after clicking off the navigation. So step #2->#3 is critical to reproducing.

As a workaround for now, @andyfleming, click off the nav somewhere first.

**Comment by DCzajkowski** [comment] 2017-08-31 22:06
If you press the little triangle at the top (the one that doesn't event have a description [#141](https://github.com/laravel/laravel.com/pull/141)) all menus expand. Then there is no problem with modifiers. This should be fixed though. Maybe make a PR to the [laravel/laravel.com](https://github.com/laravel/laravel.com)?

**Comment by laurencei** [comment] 2018-02-12 11:05
This looks to be resolved with the PR above.

If anyone still has any issues feel free to open a new ticket. Thanks

**Closed by laurencei** 2018-02-12 11:05 UTC
