### ISSUE TITLE
Illuminate\Log\LogManager 创建driver的时候为什么没把config传给prepareHandler

### ISSUE THREAD

**Issue by oyuleo** [laravel/docs#4323] opened 2018-06-10 02:22 UTC
protected function createDailyDriver(array $config)
    {
        return new Monolog($this->parseChannel($config), [
            $this->prepareHandler(new RotatingFileHandler(
                $config['path'], $config['days'] ?? 7, $this->level($config),
                $config['bubble'] ?? true, $config['permission'] ?? null, $config['locking'] ?? false
            )),
        ]);
    }

**Comment by overtrue** [comment] 2018-06-10 02:42
1. 请使用国际语言
2. 请正确并详细表达你的问题，而不是贴一段不晓得是啥的代码
3. 请正确使用 markdown 粘贴代码

**Comment by laurencei** [comment] 2018-06-23 02:13
Hi,

I'm closing this ticket as it is not clear what the problem is. Please feel free to submitting a new ticket with an exaplanation of the problem

**Closed by laurencei** 2018-06-23 02:13 UTC
